### ISSUE TITLE
The request failed with code 400 Bad Request

### ISSUE THREAD

**Issue by dietybright** [minitriga/Netbox-Device-Type-Library-Import#113]
When trying to run import script I am having below issue, any idea?

root@netbox:/opt/netbox/Netbox-Device-Type-Library-Import# source venv/bin/activate
(venv) root@netbox:/opt/netbox/Netbox-Device-Type-Library-Import# cat .env

NETBOX_URL=https://localhost
NETBOX_TOKEN=5baac1bba5e79bb222779d6b9a524e2ce09d6e93
REPO_URL=https://github.com/netbox-community/devicetype-library.git
REPO_BRANCH=master
IGNORE_SSL_ERRORS=True
#SLUGS=c9300-48u isr4431 isr4331

(venv) root@netbox:/opt/netbox/Netbox-Device-Type-Library-Import# ./nb-dt-import.py --vendors cisco

Package devicetype-library is already installed, updating /opt/netbox/Netbox-Device-Type-Library-Import/repo
/opt/netbox/Netbox-Device-Type-Library-Import/venv/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Traceback (most recent call last):
  File "/opt/netbox/Netbox-Device-Type-Library-Import/./nb-dt-import.py", line 54, in <module>
    main()
  File "/opt/netbox/Netbox-Device-Type-Library-Import/./nb-dt-import.py", line 17, in main
    netbox = NetBox(settings)
  File "/opt/netbox/Netbox-Device-Type-Library-Import/netbox_api.py", line 28, in __init__
    self.verify_compatibility()
  File "/opt/netbox/Netbox-Device-Type-Library-Import/netbox_api.py", line 50, in verify_compatibility
    version_split = [int(x) for x in self.netbox.version.split('.')]
  File "/opt/netbox/Netbox-Device-Type-Library-Import/venv/lib/python3.10/site-packages/pynetbox/core/api.py", line 109, in version
    ).get_version()
  File "/opt/netbox/Netbox-Device-Type-Library-Import/venv/lib/python3.10/site-packages/pynetbox/core/query.py", line 187, in get_version
    raise RequestError(req)
pynetbox.core.query.RequestError: The request failed with code 400 Bad Request but more specific details were not returned in json. Check the NetBox Logs or investigate this exception's error attribute.

**Comment by dietybright** [comment]
The issue is fixed now, change NETBOX_URL=https://localhost/ to actually IP address

**Comment by danner26** [comment]
I am glad you were able to figure it out! If you need anything else feel free to reach out
