### ISSUE TITLE
Errors parsing netbox Version info

### ISSUE THREAD

**Issue by dBitech** [minitriga/Netbox-Device-Type-Library-Import#124]
When attempting to run ``nb-dt-import``, the script fails against netbox 3.7.1 in the following way:

```
(venv) netbox@netbox-01 /opt/Device-Type-Library-Import# ./nb-dt-import.py
Package devicetype-library is already installed, updating /opt/Device-Type-Library-Import/repo
Traceback (most recent call last):
  File "/opt/Device-Type-Library-Import/./nb-dt-import.py", line 54, in <module>
    main()
  File "/opt/Device-Type-Library-Import/./nb-dt-import.py", line 17, in main
    netbox = NetBox(settings)
             ^^^^^^^^^^^^^^^^
  File "/opt/Device-Type-Library-Import/netbox_api.py", line 28, in __init__
    self.verify_compatibility()
  File "/opt/Device-Type-Library-Import/netbox_api.py", line 50, in verify_compatibility
    version_split = [int(x) for x in self.netbox.version.split('.')]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/Device-Type-Library-Import/netbox_api.py", line 50, in <listcomp>
    version_split = [int(x) for x in self.netbox.version.split('.')]
                     ^^^^^^
ValueError: invalid literal for int() with base 10: ''
(venv) netbox@netbox-01 /opt/Device-Type-Library-Import# 
```

**Comment by dBitech** [comment]
Resolved, this was a http vs https issue
