### ISSUE TITLE
nb-dt-import.py fails, bypasses nebox api token, asks for credentials

### ISSUE THREAD

**Issue by julianfirminger-united** [minitriga/Netbox-Device-Type-Library-Import#143]
new netbox deployment moved from Rocky93 to 94

(venv) [root@NETBOX Device-Type-Library-Import]# ./nb-dt-import.py
Package devicetype-library is already installed, updating /opt/Device-Type-Library-Import/repo
Traceback (most recent call last):
  File "/opt/Device-Type-Library-Import/./nb-dt-import.py", line 54, in <module>
    main()
  File "/opt/Device-Type-Library-Import/./nb-dt-import.py", line 17, in main
    netbox = NetBox(settings)
  File "/opt/Device-Type-Library-Import/netbox_api.py", line 28, in __init__
    self.verify_compatibility()
  File "/opt/Device-Type-Library-Import/netbox_api.py", line 50, in verify_compatibility
    version_split = [int(x) for x in self.netbox.version.split('.')]
  File "/opt/Device-Type-Library-Import/venv/lib64/python3.9/site-packages/pynetbox/core/api.py", line 106, in version
    version = Request(
  File "/opt/Device-Type-Library-Import/venv/lib64/python3.9/site-packages/pynetbox/core/query.py", line 187, in get_version
    raise RequestError(req)
pynetbox.core.query.RequestError: The request failed with code 403 Forbidden: {'detail': 'Authentication credentials were not provided.'}

**Comment by julianfirminger-united** [comment]
bad info, will repoen
