### ISSUE TITLE
Authentication credentials were not provided

### ISSUE THREAD

**Issue by tumanh** [minitriga/Netbox-Device-Type-Library-Import#159]
I am getting the error "Authentication credentials were not provided" when running the command **./nb-dt-import.py**.

```
(venv) [root@PROD-NETBOX Device-Type-Library-Import]# ./nb-dt-import.py
Package Installed https://github.com/netbox-community/devicetype-library.git
Traceback (most recent call last):
  File "/root/Device-Type-Library-Import/./nb-dt-import.py", line 54, in <module>
    main()
  File "/root/Device-Type-Library-Import/./nb-dt-import.py", line 17, in main
    netbox = NetBox(settings)
             ^^^^^^^^^^^^^^^^
  File "/root/Device-Type-Library-Import/netbox_api.py", line 28, in __init__
    self.verify_compatibility()
  File "/root/Device-Type-Library-Import/netbox_api.py", line 50, in verify_compatibility
    version_split = [int(x) for x in self.netbox.version.split('.')]
                                     ^^^^^^^^^^^^^^^^^^^
  File "/root/Device-Type-Library-Import/venv/lib64/python3.11/site-packages/pynetbox/core/api.py", line 109, in version
    ).get_version()
      ^^^^^^^^^^^^^
  File "/root/Device-Type-Library-Import/venv/lib64/python3.11/site-packages/pynetbox/core/query.py", line 187, in get_version
    raise RequestError(req)
pynetbox.core.query.RequestError: The request failed with code 403 Forbidden: {'detail': 'Authentication credentials were not provided.'}
```
**ENV file:**

```
NETBOX_URL=http://172.16.10.137:8000
NETBOX_TOKEN=78127a3dcb1095579b84f3d3fb3da8e9175374c9
REPO_URL=https://github.com/netbox-community/devicetype-library.git
REPO_BRANCH=master
IGNORE_SSL_ERRORS=False
#SLUGS=c9300-48u isr4431 isr4331
```

Token info:

```
[root@PROD-NETBOX Device-Type-Library-Import]# curl -X POST \
> -H "Content-Type: application/json" \
> -H "Accept: application/json; indent=4" \
> http://172.16.10.137:8000/api/users/tokens/provision/ \
> --data '{
>     "username": "admin",
>     "password": "Hvktmmat10@"
> }'
{
    "id": 2,
    "url": "http://172.16.10.137:8000/api/users/tokens/2/",
    "display_url": "http://172.16.10.137:8000/users/tokens/2/",
    "display": "78127a3dcb1095579b84f3d3fb3da8e9175374c9",
    "user": {
        "id": 1,
        "url": "http://172.16.10.137:8000/api/users/users/1/",
        "display": "admin",
        "username": "admin"
    },
    "created": "2024-11-08T02:34:52.935327Z",
    "expires": null,
    "last_used": null,
    "key": "78127a3dcb1095579b84f3d3fb3da8e9175374c9",
    "write_enabled": true,
    "description": "",
    "allowed_ips": []
}
```

I was installed with docker-compose:

Version:
```
NetBox release	NetBox Community v4.1.6 (2024-10-31)
Python version	3.12.3
Django version	5.0.9
PostgreSQL version	PostgreSQL 16.4 on x86_64-pc-linux-musl, compiled by gcc
Database name	netbox
Database size	22 MB
RQ workers	1 (default queue)
```

**Comment by benasse** [comment]
You should check : https://github.com/netbox-community/Device-Type-Library-Import/issues/144#issuecomment-2273916604

**Comment by tumanh** [comment]
Thanks! I'm done!
