### ISSUE TITLE
repo_url is not set ? 

### ISSUE THREAD

**Issue by spastro** [minitriga/Netbox-Device-Type-Library-Import#56]
Hi all, just setting this up and getting the following error running ./nb-dt-import.py  as per guide.

Any help?

./nb-dt-import.py
Traceback (most recent call last):
  File "./nb-dt-import.py", line 10, in <module>
    import settings
  File "/opt/Netbox-Device-Type-Library-Import/settings.py", line 25, in <module>
    raise EnvironmentError("Failed because {} is not set.".format(var))
OSError: Failed because REPO_URL is not set.

**Comment by spastro** [comment]
my mistake with the .env rename
